[build]
command = "yarn build"
publish = "build"

[context."feat/i18n"]
command = "yarn crowdin:sync && yarn build"
publish = "build"

[[redirects]]
from = "/en/*"
to = "/:splat"

[[redirects]]
from = "/docs/api/rust/*"
to = "https://docs.rs/tauri/1.0.0-rc.0/tauri/"

[[redirects]]
from = "/partners"
to = "/#sponsors"

[[redirects]]
from = "/docs/guides/*"
to = "/v1/guides/features/:splat"

[[redirects]]
from = "/docs/*"
to = "/v1/:splat"

[[redirects]]
from = "/api/*"
to = "/v1/api/:splat"

[[redirects]]
from = "/guides/*"
to = "/v1/guides/:splat"

[[redirects]]
from = "/v1/guides/getting-started/setup*"
to = "/v1/guides/getting-started/prerequisites/"

[[redirects]]
from = "/v1/guides/examples/*"
to = "/v1/guides/features/:splat"

[[redirects]]
from = "/v1/about/*"
to = "/about/:splat"
