[[redirects]]
from = "/en/*"
to = "/:splat"

[[redirects]]
from = "/docs/api/rust/*"
to = "https://docs.rs/tauri/1/tauri/"

[[redirects]]
from = "/partners"
to = "/#sponsors"

[[redirects]]
from = "/docs/guides/*"
to = "/v1/guides/features/:splat"

[[redirects]]
from = "/docs/*"
to = "/v1/:splat"

[[redirects]]
from = "/api/*"
to = "/v1/api/:splat"

[[redirects]]
from = "/guides/*"
to = "/v1/guides/:splat"

[[redirects]]
from = "/v1/guides/getting-started/setup*"
to = "/v1/guides/getting-started/prerequisites/"

[[redirects]]
from = "/v1/guides/examples/*"
to = "/v1/guides/features/:splat"

[[redirects]]
from = "/v1/about/*"
to = "/about/:splat"

[[redirects]]
from = "/v1/guides/architecture/brownfield"
to = "/v1/guides/architecture/inter-process-communication/brownfield"

[[redirects]]
from = "/v1/guides/architecture/isolation"
to = "/v1/guides/architecture/inter-process-communication/isolation"

[[redirects]]
from = "/v1/guides/getting-started/tauri-cli"
to = "/v1/guides/getting-started/setup/html-css-js"

[[redirects]]
from = "/blog/tauri_1_0"
to = "/blog/2022/06/19/tauri-1-0"

[[redirects]]
from = "/release-notes"
to = "/v1/api/release-notes"
