# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: i18n-preview

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Setup yarn
        run: yarn install --frozen-lockfile
      - name: Update config
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        run: node ./.scripts/i18n-preview.js
      - name: Create timestamp file
        # This is done so that there is always a change in the PR so a re-deploy is triggered
        run: date > timestamp.txt
      - name: Create pull request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              owner,
              repo,
              title: 'i18n Preview',
              head: 'i18n-preview',
              base: '${{ github.ref_name }}',
              draft: true
            });

#       - name: Configure git
#         run: |
#           git config --global user.name 'Tauri Bot'
#           git config --global user.email 'tauri-bot@tauri.studio'
#       - name: Create pull request
# soft fork of https://github.com/peter-evans/create-pull-request for security purposes
#         uses: tauri-apps/create-pull-request@v3
#         with:
#           title: i18n Preview
#           branch: i18n-preview
#           draft: true
#           token: ${{ secrets.ORG_TAURI_BOT_PAT }}
#           body: |
#             **DO NOT MERGE**

#             This is used to create an constantly-refreshed deploy preview for Crowdin translations.

#             A new deploy is scheduled for 12am UTC every day.
